[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "^1.3.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "^1.6.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.1.1"

